# Generated by Django 5.1.7 on 2025-06-01 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'items', 'verbose_name_plural': 'shop'},
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('laptop', 'laptop'), ('desktop', 'desktop'), ('all in one computer', 'all_in_one_computer'), ('mobile', 'mobile'), ('tablet', 'tablet'), ('accessories', 'accessories'), ('gaming', 'gaming'), ('printer', 'printer'), ('camera', 'camera'), ('audio', 'audio'), ('networking', 'networking'), ('software', 'software'), ('home appliances', 'home_appliances'), ('smart home devices', 'smart_home_devices')], default='electronics', max_length=100, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='photos/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Product Name'),
        ),
    ]
