# Generated by Django 5.1.7 on 2025-06-02 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='time',
            name='date',
            field=models.DateField(),
        ),
    ]
