# Generated by Django 5.1.7 on 2025-06-02 07:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_time_time_alter_time_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
