# Generated by Django 5.1.7 on 2025-06-14 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_advertisement'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='advertisements', to='products.product'),
        ),
    ]
